In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

from tensorflow import keras
from tensorflow.keras.layers import Dense

In [2]:
df = pd.read_csv("internship_train.csv")

In [3]:
y = df.pop("target")
train_target = np.array(y)
train_data = np.array(df)
#test = np.array(x.loc[1])
#res = y.loc[1]
#print(test)
#print("#"*20)
#print(res)
print(train_target[:5])
print(train_data[:5])

[20.10747174 61.76371332 74.651162   69.42464537 66.76730392]
[[ 2.36000000e+02  4.88000000e+02  1.60000000e+01  2.21000000e+02
   3.82000000e+02  9.70000000e+01 -4.47213595e+00  1.07471738e-01
   0.00000000e+00  1.32000000e+02  2.81000000e+02  3.36000000e+02
   9.90000000e+01  3.88009813e+00  1.79750241e+00  3.25247547e+00
   1.21319808e+01  3.09136068e+00  5.63031887e+00  4.46637286e+00
   2.51120335e+00  5.98272404e+00  4.54115934e+00  1.27404763e+01
   1.26349291e+01  4.05029385e+00  1.18272453e+01  3.56832072e+00
   1.34205371e+01  8.25180666e+00  2.28790040e+00  1.48344300e+01
   8.22532252e-02  2.97556092e+00  5.22375269e+00  1.21228674e+00
   7.30279656e+00  7.08314917e+00  3.61034992e+00  7.76751180e+00
   7.82965727e+00  8.39535614e+00  1.58371120e+00  1.01250197e+01
   1.33408737e+01  8.70541652e-01  1.96293699e+00  7.46666618e+00
   1.15477942e+01  8.82291647e+00  9.04642441e+00  7.89553517e+00
   1.10106774e+01]
 [ 3.86000000e+02  2.06000000e+02  3.57000000e+02  2.32000000

In [4]:
std = train_data.std(axis=0)
train_data /= std

In [5]:
train_data[:5]

array([[ 1.63507835,  3.38838535,  0.11102878,  1.53169984,  2.65386916,
         0.67207856, -0.63541518,  0.37228572,  0.        ,  0.91278786,
         1.94648179,  2.32565664,  0.6860246 ,  0.89591368,  0.41624617,
         0.74964151,  2.79178869,  0.71592312,  1.30226683,  1.03213785,
         0.58056823,  1.38164843,  1.04814322,  2.94309276,  2.9077871 ,
         0.9334453 ,  2.72901842,  0.82390555,  3.09588627,  1.91079114,
         0.52871781,  3.43179247,  0.01899832,  0.68720456,  1.20554085,
         0.27963672,  1.68675653,  1.63679297,  0.83312195,  1.79485834,
         1.80984384,  1.94537759,  0.36542765,  2.33839302,  3.08075893,
         0.20144371,  0.45315235,  1.72214919,  2.66563565,  2.04091947,
         2.09101083,  1.82561969,  2.54108823],
       [ 2.67432306,  1.430343  ,  2.47732972,  1.6079383 ,  0.0069473 ,
         1.37187169,  1.1097049 ,  2.64552863,  2.00000263,  0.98885351,
         0.75504098,  0.85135645,  0.90084039,  2.79383395,  2.47097063,
   

In [7]:
model = keras.Sequential()
model.add(Dense(64, activation="relu", input_shape=(train_data.shape[1],)))
model.add(Dense(32, activation="relu"))
model.add(Dense(1))

model.compile(loss="mse", metrics=[keras.metrics.RootMeanSquaredError()], optimizer=keras.optimizers.Adam(learning_rate=0.01))

#history = model.fit(x,y, epochs=40)

#plt.plot(history.history["loss"])
#plt.grid(True)
#plt.show()

In [8]:
model.load_weights("3_q_regresion_model.h5")

In [9]:
test_df = pd.read_csv("internship_hidden_test.csv")
test_df

0    1    2    3    4    5         6         7  8    9  ...  \
0     259  388  402  340  156  382  3.316625  0.218760  1  164  ...   
1     441  192  381  421  452  123 -8.888194  0.700228  0  349  ...   
2      83  129  107  156  247  191  2.645751  0.494556  1  297  ...   
3     183  438  191  116  491  403 -6.164414  0.511117  0  272  ...   
4     449  156  310  188  279  465  8.000000  0.756416  1   90  ...   
...   ...  ...  ...  ...  ...  ...       ...       ... ..  ...  ...   
9995  221  246  314  406  464  317  6.708204  0.436684  1  205  ...   
9996  152  157   32  133  369  261  5.656854  0.986208  1  457  ...   
9997  349  240  355   97   93  176  4.690416  0.830543  1  287  ...   
9998  427   70   63  265   62  150  4.000000  0.502337  1  124  ...   
9999  144  216   66  452  382  307  9.539392  0.986542  1   40  ...   

             43         44         45         46         47         48  \
0      7.163474  10.227235   0.889111   9.190222   4.670908   0.931525   
1     10.619064   9.339161   4.221861   0.595563  13.865748   0.328453   
2      1.819890  10.670237  10.350867   5.134417   5.898995   8.374986   
3      4.168135  12.782579   0.513072   0.321295  11.334062  11.735511   
4      7.908122   1.140498  14.165074   7.688796   5.079241   8.152186   
...         ...        ...        ...        ...        ...        ...   
9995   1.272356  12.306512   7.778209   5.698493  10.023215   4.959409   
9996   2.331195  13.176561   6.697370   4.119232   2.190155  14.555999   
9997  14.423037   0.941523   3.555292  12.572057   7.058367  12.999451   
9998   1.154640   1.593796   9.902159   2.548667  11.339210  14.192310   
9999   2.794024  14.724772   3.093617   3.681825  11.427112   5.748047   

             49         50         51         52  
0      7.634177   0.158196  13.432551   2.511191  
1     11.507599   9.107966   1.302407  11.105604  
2      4.638049   3.160023   2.243799   5.073030  
3      1.911520   8.365676   4.877288  11.601819  
4      1.680403  13.215111   5.823109   1.038015  
...         ...        ...        ...        ...  
9995   4.056025   4.642375   4.533745   6.754558  
9996   7.786794   9.414130   5.413161   4.134093  
9997   1.901825   5.100031   1.498432   8.093801  
9998  14.142207   9.966924   8.538981   7.036367  
9999   8.053866   0.729627   0.767049   9.541795  

[10000 rows x 53 columns]

In [10]:
test_data = np.array(test_df)
test_data /= std
test_data

array([[1.7944292 , 2.69404409, 2.78959818, ..., 0.0365657 , 3.10589838,
        0.57954283],
       [3.05537945, 1.33313522, 2.6438729 , ..., 2.1052356 , 0.30114496,
        2.56299575],
       [0.57504874, 0.89570023, 0.74250499, ..., 0.73041488, 0.51881519,
        1.17077414],
       ...,
       [2.41797603, 1.66641903, 2.46345113, ..., 1.17883257, 0.34647004,
        1.86791991],
       [2.95838328, 0.48603888, 0.43717583, ..., 2.30377711, 1.97439847,
        1.62388087],
       [0.99767492, 1.49977712, 0.45799373, ..., 0.16864757, 0.17735849,
        2.20209374]])

In [11]:
y_pred = model.predict(test_data)
y_pred

313/313 [==============================] - 0s 759us/step


array([[10.783811],
       [80.18466 ],
       [ 8.333396],
       ...,
       [23.666378],
       [16.767773],
       [93.42528 ]], dtype=float32)

In [12]:
fin_df = pd.DataFrame(data=y_pred)
fin_df.columns = ['target']
fin_df

target
0     10.783811
1     80.184662
2      8.333396
3     38.694794
4     65.770569
...         ...
9995  45.707855
9996  33.688820
9997  23.666378
9998  16.767773
9999  93.425278

[10000 rows x 1 columns]

In [13]:
fin_df.to_csv('model_prediction_1.csv', index=False)

In [14]:
pd.read_csv("model_prediction.csv")

target
0     36.757744
1     37.144844
2     42.197900
3     37.090797
4     44.226242
...         ...
9995  39.654290
9996  45.574333
9997  44.162903
9998  42.342422
9999  45.020890

[10000 rows x 1 columns]